# Calendar Repairer Configuration
# Repairs keyword-prefixed events in Google Calendar

version: 1

# Plugin pipeline order - CalendarRepairer must run BEFORE other enrichers
pipeline:
  order: ["UndefinedGuard", "CalendarRepairer", "KeywordEnricher", "command_handler"]

# Calendar Repairer configuration
calendar_repairer:
  enabled: true

  # Prefixes that are reserved and never rewritten
  reserved_prefixes: ["ACTION", "MEETING", "CALL"]

  # Fallback behavior for read-only calendars
  readonly_fallback: "internal_enrich_only"

  # Google Calendar API patch settings
  google_patch:
    send_updates: "none"  # Don't notify attendees
    use_if_match: true    # Use ETag for conflict detection

  # Idempotency settings to prevent duplicate processing
  idempotency:
    marker_key: "chronos.cleaned"
    marker_value: "v1"
    signature_fields: ["original_summary", "start", "recurrence"]

  # Series event handling policy
  series_policy:
    edit_master_if_keyword_on_master: true
    edit_instance_if_keyword_on_instance: true
    do_not_edit_past_instances: true

# Date parsing configuration
parsing:
  accept_date_separators: [".", "-", "/"]
  day_first: true           # For ambiguous dates like 03/07
  year_optional: true       # Allow dates without year
  strict_when_ambiguous: true  # Require manual review for ambiguous dates

# Repair rules for different event types
rules:
  # Birthday events
  - id: "bday"
    keywords: ["BDAY", "BIRTHDAY", "GEB", "GEBURTSTAG"]
    title_template: "🎉 Birthday: {name} ({date_display}){age_suffix}"
    age_suffix_template: " – turns {age}."
    all_day: true
    rrule: "FREQ=YEARLY"
    leap_day_policy: "FEB_28"
    enrich:
      event_type: "birthday"
      tags: ["personal", "birthday"]
      sub_tasks:
        - { text: "Buy card", completed: false }
        - { text: "Get gift", completed: false }
        - { text: "Call to congratulate", completed: false }

  # Birthday warnings
  - id: "bdaywarn"
    keywords: ["BDAYWARN", "BIRTHDAYWARN", "GEBWARN", "GEBURTSTAGWARN"]
    title_template: "⏰ {name}'s birthday in {warn_abs_days} days ({date_day_month})"
    all_day: true
    rrule: "FREQ=YEARLY"
    warn_offset_days: -4
    link_to_rule: "bday"
    enrich:
      event_type: "birthday_warning"
      tags: ["personal", "reminder"]
      sub_tasks:
        - { text: "Prepare birthday plans", completed: false }

  # Memorial/Death anniversaries
  - id: "rip"
    keywords: ["RIP", "DEATH", "MEMORIAL", "TOD", "GEDENKEN"]
    title_template: "🕯️ In memory of {name} († {date_display}){years_since_suffix}"
    years_since_suffix_template: " – {years_since}th."
    all_day: true
    rrule: "FREQ=YEARLY"
    enrich:
      event_type: "memorial"
      tags: ["memorial"]
      sub_tasks:
        - { text: "Flowers/visit", completed: false }
        - { text: "Light candle", completed: false }

  # Memorial warnings
  - id: "ripwarn"
    keywords: ["RIPWARN", "MEMORIALWARN", "TODWARN", "GEDENKWARN"]
    title_template: "🕯️ Memorial for {name} in {warn_abs_days} days ({date_day_month})"
    all_day: true
    rrule: "FREQ=YEARLY"
    warn_offset_days: -3
    link_to_rule: "rip"
    enrich:
      event_type: "memorial_warning"
      tags: ["memorial", "reminder"]
      sub_tasks:
        - { text: "Plan memorial activities", completed: false }

  # Generic anniversaries
  - id: "anniv"
    keywords: ["ANNIV", "ANNIVERSARY", "JUBI", "JUBILÄUM"]
    title_template: "🎖️ {label}: {name_or_label} since {date_display}{years_since_suffix}"
    label_from_payload: true
    years_since_suffix_template: " – {years_since}th."
    all_day: true
    rrule: "FREQ=YEARLY"
    enrich:
      event_type: "anniversary"
      tags: ["anniversary"]
      sub_tasks:
        - { text: "Plan celebration", completed: false }

  # Anniversary warnings
  - id: "annivwarn"
    keywords: ["ANNIVWARN", "ANNIVERSARYWARN", "JUBIWARN", "JUBILÄUMWARN"]
    title_template: "⏰ {label}: {name_or_label} in {warn_abs_days} days ({date_day_month})"
    all_day: true
    rrule: "FREQ=YEARLY"
    warn_offset_days: -7
    link_to_rule: "anniv"
    enrich:
      event_type: "anniversary_warning"
      tags: ["anniversary", "reminder"]
      sub_tasks:
        - { text: "Prepare anniversary plans", completed: false }

# Auto-warning generation (optional feature)
auto_warning:
  enabled: false  # Disabled by default - users can create manual warnings
  offset_days: -4
  link_bi_directional: true

# Metrics and monitoring configuration
metrics:
  enabled: true
  export_interval_seconds: 300  # Export metrics every 5 minutes

# Logging configuration
logging:
  level: "INFO"
  structured: true
  include_fields: ["calendar_id", "event_id", "rule_id", "elapsed_ms", "outcome"]