# Basic CalDAV Configuration Example
# Minimal setup for local Radicale server

version: 1

# CalDAV as primary backend
calendar_source:
  type: "caldav"
  timezone_default: "Europe/Berlin"

# Basic CalDAV configuration
caldav:
  calendars:
    - id: "personal"
      alias: "Personal Calendar"
      url: "http://localhost:5232/user/personal/"
      read_only: false
      timezone: "Europe/Berlin"

  # No authentication for local server
  auth:
    mode: "none"

  # Basic transport settings
  transport:
    verify_tls: false
    connect_timeout_s: 5
    read_timeout_s: 15

  # Use sync-collection for efficiency
  sync:
    use_sync_collection: true
    window_days: 90
    parallel_requests: 1

  # Enable conflict detection
  write:
    if_match: true
    retry_conflict: 1
    include_vtimezone: true

# Database configuration
database:
  url: "sqlite:///data/chronos.db"
  echo: false

# API configuration
api:
  api_key: "your-secure-api-key"
  host: "0.0.0.0"
  port: 8080
  cors_origins: ["*"]

# Scheduler configuration
scheduler:
  sync_interval: 3600  # 1 hour
  max_workers: 2
  enabled: true

# Disable optional features
analytics:
  enabled: false

ai:
  enabled: false

notifications:
  enabled: false

# Logging
logging:
  level: "INFO"
  structured: true
  file: "logs/chronos.log"